[package]
name = "shared"
version = "0.1.0"
authors = ["Tommy Volk <tvolk131@gmail.com>"]
edition = "2018"

[dependencies]
bson = "1.2.2"
chrono = "0.4.19"
prost = "0.7.0"
tonic = "0.4.2"

[build-dependencies]
tonic-build = "0.4.2"